### ISSUE TITLE
Npm

### ISSUE THREAD

**Issue by Sempai-07** [risticks/rist.js#1]
Почему же `rist.js` не сделать библиотекой `npm`?

Использование `rist.js` как библиотеку `npm` даст преимущества, такие как:
1. Удобство установки и обновления через `npm`.
2. Большая доступность для разработчиков JavaScript.
3. Легкая интеграция с другими инструментами разработки.

Но итоговое мнение остаётся за вами – делать или нет. Но действительно, гораздо проще установить пакет через `npm`, чем скачивать его с какого-либо другого источника :). 😅

**Comment by Drygoy** [comment]
Ок, мы хотим сделать

**Comment by Sempai-07** [comment]
❤️
