### ISSUE TITLE
Constructor app

### ISSUE THREAD

**Issue by Sempai-07** [risticks/rist.js#2]
Почему же, не переместить все вызовы методов `app`... в конструкторе класса?

## Пример
```js
const app = new App({
  templatesDirectory: "public",
  stylesDirectory: "/static/css",
  scriptsDirectory: "/static/scripts",
  imagesDirectory: "/static/images",
  otherDirectory: "/static/other",
  scssSourceDirectory: "public/static/scss",
  scssOutputDirectory: "public/static/css",
  notFoundPage: "404.html",
});
```

## Плюсы
Перемещение вызовов методов `app...` в конструкторе приводит к следующим преимуществам:

1. Упрощение инициализации: Все параметры передаются в конструкторе одновременно, что делает инициализацию компактной и удобной.

2. Улучшение читаемости: Код становится более линейным и понятным, так как все параметры настроек находятся в одном месте.

3. Централизация настроек: Группировка связанных параметров в конструкторе упрощает понимание зависимостей и повышает модульность кода.

4. Расширяемость: Добавление новых параметров требует изменений только в конструкторе, что упрощает расширение функциональности и обновление настроек.

Но, как я говорил - всё остаётся за вами 😀

**Comment by Drygoy** [comment]
Подумаем
